# Evidence-Grade Contacts PoC Configuration
# Based on README.md and WARP.md specifications

parser_version: "0.1.0-poc"

# Input configuration
inputs:
  urls_file: "./input_urls.txt"

# Processing scope - corporate website sections
scope:
  include_paths:
    # General company info
    - "/about"
    - "/who-we-are"
    - "/overview"

    # People/Team variants
    - "/team"
    - "/our-team"
    - "/people"
    - "/our-people"
    - "/staff"
    - "/professionals"
    - "/attorneys"
    - "/lawyers"

    # Leadership/Management variants
    - "/leadership"
    - "/leadership-team"
    - "/management"
    - "/management-team"
    - "/executives"
    - "/board"

    # Contact/Imprint
    - "/contacts"
    - "/contact"
    - "/imprint"
    - "/impressum"

    # Optional news/press
    - "/news"      # Optional from README
    - "/press"     # Optional from README

# Compliance and legal framework
compliance:
  enforce_robots_and_tos: true
  data_minimization: "business_contacts_only"
  deletion_requests: "manual"
  red_flag_domains:
    - "linkedin.com"
    - "x.com"
    - "twitter.com"
    - "facebook.com"
    - "meta.com"
    - "instagram.com"

# Rendering strategy (static-first with targeted escalation)
renderer:
  mode: "static-first"
  static:
    burst_rps: 1.0
  headless:
    enabled: true
    max_pct_per_domain: 0.2     # ≤ 20% per domain
    burst_rps: 0.2

# Timeouts and budgets
timeouts:
  budget_ms_per_url: 12000

# Backoff and retry policy
backoff:
  cooldown_on_403:
    - "5m"
    - "15m" 
    - "60m"

# Mini Evidence Package configuration
evidence_pack:
  required_fields:
    - "source_url"
    - "selector_or_xpath"
    - "verbatim_quote"
    - "dom_node_screenshot"
    - "timestamp"
    - "parser_version"
    - "content_hash"
  storage_dir: "./out/evidence"
  screenshot_format: "png"
  content_hash_algorithm: "sha256"

# Operational budgets and observability (PoC)
ops:
  concurrency:
    max_workers: 4   # runner-level parallelism (suggested)
  headless:
    per_domain_budget: 2   # hard cap per domain (pages per run)
    global_budget: 10       # hard cap per run
    max_share_pct: 0.2      # soft quota (existing guardrail)
    target_paths_only: true # only /our-team|/team|/leadership|/management|/people
  timeouts:
    static_fetch_s: 8       # static fetch timeout
    prefilter_head_s: 2     # HEAD prefilter timeout
    dom_sweep_budget_s: 8   # per-page DOM sweep budget
    deep_pass_budget_s: 3   # optional deep pass budget
  d1_profile:
    max_per_listing: 5      # D=1 follow-ups per listing page
  logging:
    ops_json: true          # print JSON ops logs when EGC_OPS_JSON=1
  cost:
    rate_static_per_min: 0.00       # $ per minute of static (fetch+extract)
    rate_headless_per_min: 0.00     # $ per minute of headless (Playwright)
    fee_static_per_page: 0.00       # optional fixed $ per static page processed
    fee_headless_per_page: 0.00     # optional fixed $ per headless page processed

# SMTP probe configuration
smtp_probe:
  enabled: true
  free_providers_blocklist: true
  cache_ttl_days: 7

# Output configuration
exports:
  out_dir: "./out"
  formats: ["csv", "json"]
  exclude_unverified: true

# Logging
logging:
  level: "INFO"
